---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
  when: ansible_os_family == "Debian"

- name: Install Python pip
  apt:
    name: python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install Python psycopg2
  apt:
    name: python3-psycopg2
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create PostgreSQL database
  postgresql_db:
    name: semaphore
    state: present

- name: Create PostgreSQL user
  postgresql_user:
    name: semaphore
    password: semaphorepassword
    priv: "ALL"
    db: semaphore
    state: present