---
- name: Download Semaphore package
  get_url:
    url: https://github.com/semaphoreui/semaphore/releases/download/v2.10.35/semaphore_2.10.35_linux_386.deb
    dest: /tmp/semaphore_2.10.35_linux_386.deb

- name: Install Semaphore package
  apt:
    deb: /tmp/semaphore_2.10.35_linux_386.deb
    state: present

- name: Add a group semaphore
  ansible.builtin.group:
    name: semaphore
    state: present

- name: Add user to remote hosts
  ansible.builtin.user:
    name: semaphore
    home: /home/semaphore
    shell: /bin/bash
    create_home: yes
    group: semaphore

- name: Copy config.json
  ansible.builtin.copy:
    src: files/config.json
    dest: /home/semaphore/config.json
    owner: semaphore
    group: semaphore
    mode: 0644

- name: Add semaphore user
  become: yes
  become_user: semaphore
  ansible.builtin.user:
    name: semaphore
    state: present

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Copy semaphore.service
  ansible.builtin.copy:
    src: files/semaphore.service
    dest: /etc/systemd/system/semaphore.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable service semaphore.service
  ansible.builtin.systemd:
    name: semaphore.service
    state: started
    enabled: true

