- name: "Replace postgres config"
  ansible.builtin.copy:
    src: files/pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600

- name: Restart PostgreSQL server
  ansible.builtin.service:
    name: postgresql@12-main
    state: restarted
    enabled: yes


